name: Lint Code

on:
  push:
    branches:
      - main
      - development
      
jobs:
  LintCode:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Super Linter
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_CSS: false
        VALIDATE_DART: false
        VALIDATE_DOCKERFILE_HADOLINT: false
        VALIDATE_JAVA: false
        VALIDATE_HTML: false
        VALIDATE_JAVASCRIPT_ES: false
        VALIDATE_MARKDOWN: false
        VALIDATE_SQL: false
        YAML_CONFIG_FILE: .yaml-lint.yml
        
