name: Run Tests

on:
  push:
    branches:
      - main
      - development

jobs:
  RunAllTests:        
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
        
    - name: checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./testing/automated
      
    - name: executer Test
      run: go test -v ./EZAudit/executer
