name: build windows
on:
  push:
    branches:
      - main
      - development

jobs:
  build:        
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
        
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: go build ./EZAudit
